config/routes.rb
Rails.application.routes.draw do
	get 'users/index'
	resources :tags do
			get '/recipes', to: 'tags#tag_recipes'
			collection do
				get :list
			end
	end

	resources :manage_users
	resources :manage_recipes

	resources :instructions
	resources :ingredients
	resources :recipes do
		collection do
			get :my_recipes
				get :discover
				get :import_recipe
				post :import
		end
	end
	devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

	root 'recipes#discover'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
	before_save :titleize_name
	has_many_attached :pictures
	has_one_attached :header
	has_many_attached :original_recipe_photos

	has_many :ingredients, dependent: :destroy, inverse_of: :recipe
	has_many :instructions, dependent: :destroy, inverse_of: :recipe
	has_many :recipe_tags, dependent: :destroy
	has_many :tags, through: :recipe_tags

	accepts_nested_attributes_for :ingredients, :instructions, allow_destroy: true, reject_if: :all_blank
	validates :name, presence:



	def titleize_name
		self.name = self.name.titleize
	end

	def original_recipe_as_thumbnail(op)
		op.variant(resize_to_limit: [300, 300]).processed
	end



	def self.tagged_with(name)
    Tag.find_by!(name: name).recipes
  end

  def self.tag_counts
    Tag.select('tags.*, count(recipe_tags.tag_id) as count').joins(:recipe_tags).group('recipe_tags.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]
	before_action :authenticate_user!, only: %i[ new edit create udpate destroy ]

	# GET /recipes or /recipes.json
	def index
			@q = Recipe.ransack(params[:q])
			@recipes = @q.result(distinct: true).includes(:ingredients, :tags).page params[:page]
			# @recipes = @q.result.paginate(page: params[:page], per_page: 5)
		# @recipes = Recipe.all
	end

	# GET /recipes/1 or /recipes/1.json
	def show
	end

	def my_recipes
		@q = Recipe.where(user_id: current_user.id).ransack(params[:q])
		@recipes = @q.result(distinct: true).includes(:ingredients, :tags).page params[:page]
	end

	def discover
		@q = Recipe.ransack(params[:q])
		@recipes = @q.result(distinct: true).includes(:ingredients, :tags).page(params[:page]).per(4)

		count = Recipe.count
		random_offset = rand(count)
		@carousel = Recipe.offset(random_offset).first(5)

		@breakfast = Tag.find_by(name: "Breakfast")
		@dinner = Tag.find_by(name: "Dinner")
		@sides = Tag.find_by(name: "Side Dishes")
		@snacks = Tag.find_by(name: "Snacks")
		@bread = Tag.find_by(name: "Bread")
		@dessert = Tag.find_by(name: "Dessert")
		@drinks = Tag.find_by(name: "Drinks")
		@christmas = Tag.find_by(name: "Christmas")
	end

	def import_recipe
	end

	def import
		begin 
			doc = Nokogiri::HTML(URI.open(params["name"]))
			js = doc.at('script[type="application/ld+json"]').text
			jsParse = JSON[js]

			recipe_from_import = base_recipe(jsParse)

			if !recipe_from_import.nil?
				@recipe = Recipe.new
				@recipe.user_id = current_user.id

				@recipe.name = deep_find_value_with_key(recipe_from_import, "name").nil? ? "" : deep_find_value_with_key(recipe_from_import, "name")
				@recipe.description = deep_find_value_with_key(recipe_from_import, "description").nil? ? "" : deep_find_value_with_key(recipe_from_import, "description")
				@recipe.servings = deep_find_value_with_key(recipe_from_import, "recipeYield").nil? ? "" : deep_find_value_with_key(recipe_from_import, "recipeYield").first.to_i
				@recipe.prep_time = deep_find_value_with_key(recipe_from_import, "prepTime").nil? ? "" : ActiveSupport::Duration.parse(deep_find_value_with_key(recipe_from_import, "prepTime")).in_minutes
				@recipe.prep_time_descriptor = "min"
				@recipe.cook_time = deep_find_value_with_key(recipe_from_import, "cookTime").nil? ? "" : ActiveSupport::Duration.parse(deep_find_value_with_key(recipe_from_import, "cookTime")).in_minutes
				@recipe.cook_time_descriptor = "min"

				@recipe.calories = deep_find_value_with_key(recipe_from_import, "calories"),nil? ? "" : deep_find_value_with_key(recipe_from_import, "calories")


				@recipe.original_url = params["name"]
				@recipe.imported_recipe = true


				# original_author = deep_find_value_with_key(deep_find_value_with_key(recipe_from_import, "author"), "name")

				
				# Tentative Image importer
				# downloaded_image = recipe_from_import["image"]["url"].nil? ? open(recipe_from_import["image"][0]) : open(recipe_from_import["image"]["url"])
				# if !downloaded_image.nil?
				# 	@recipe.header.attach(io: downloaded_image, filename: "foo.jpg")
				# end

				#Ingredientes
				deep_find_value_with_key(recipe_from_import, "recipeIngredient").each_with_index do |ingredient, index|
					@recipe.ingredients.build(ingredient: ingredient, order_number: index)
				end

				#Instructions
				deep_find_value_with_key(recipe_from_import, "recipeInstructions").each_with_index do |instruction, index|
					@recipe.instructions.build(step: instruction["text"], step_number: index)
				end
			end

			respond_to do |format|
				if @recipe.present? && @recipe.save
					format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
					format.json { render :show, status: :created, location: @recipe }
				else
					format.html { redirect_to recipes_url, alert: "Unable to import Recipe. No recipe found" }
					format.json { head :no_content }
				end
			end
		rescue => e
			respond_to do |format|
				format.html { redirect_to recipes_url, alert: "Unable to import Recipe. Import not allowed on host website" }
				format.json { head :no_content }
			end
		end
	end

	# GET /recipes/new
	def new
		@recipe = Recipe.new
			@recipe.ingredients.build
			@recipe.instructions.build
	end

	# GET /recipes/1/edit
	def edit
	end

	# POST /recipes or /recipes.json
	def create
		@recipe = Recipe.new(recipe_params)
			@recipe.user_id = current_user.id

		respond_to do |format|
		if @recipe.save
			format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
			format.json { render :show, status: :created, location: @recipe }
		else
			format.html { render :new, status: :unprocessable_entity }
			format.json { render json: @recipe.errors, status: :unprocessable_entity }
		end
		end
	end

	# PATCH/PUT /recipes/1 or /recipes/1.json
	def update
			if @recipe.user_id == current_user.id || current_user.super_user?
			respond_to do |format|
			if @recipe.update(recipe_params)
				format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
				format.json { render :show, status: :ok, location: @recipe }
			else
				format.html { render :edit, status: :unprocessable_entity }
				format.json { render json: @recipe.errors, status: :unprocessable_entity }
			end
			end
			else
				redirect_to @recipe, notice: "You do not have permission to udpate this recipe"
			end
	end

	# DELETE /recipes/1 or /recipes/1.json
	def destroy
			if @recipe.user_id == current_user.id
			@recipe.destroy

			respond_to do |format|
			format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
			format.json { head :no_content }
			end
			else
				redirect_to @recipe, notice: "You do not have permission to delete this recipe"
			end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_recipe
		@recipe = Recipe.find(params[:id])
		end

		# Only allow a list of trusted parameters through.
		def recipe_params
		params.require(:recipe).permit(:name, :user_id, :description, :servings, :prep_time, :prep_time_descriptor, :cook_time, :cook_time_descriptor, :rest_time, :rest_time_descriptor, :total_time, :total_time_descriptor, :calories, :page, :header, :tag_list, :tag, {tag_ids: []}, :tag_ids, :ingredient_id, ingredients_attributes: [:_destroy, :id, :ingredient, :order_number], instructions_attributes: [:_destroy, :id, :step_number, :step], pictures: [], original_recipe_photos: [])
		end

		def deep_find_value_with_key(data, desired_key)
			if data.kind_of?(Array)
				data.each do |value|
					if found = deep_find_value_with_key(value, desired_key)
						return found
					end
				end
			elsif data.kind_of?(Hash)
				if data.key?(desired_key)
					data[desired_key]
				else
					data.each do |key, val|
						if found = deep_find_value_with_key(val, desired_key)
							return found
						end
					end
				end
			end
		end

		def base_recipe(data)
			if data.is_a?(Hash)
				data.each do |key, value|
					if key == "@type" 
						if value.is_a?(Array)
							value.each do |item|
								if item == "Recipe"
									return data
								end
							end
						elsif value == "Recipe"
							return data
						end
					elsif value.is_a?(Hash) || value.is_a?(Array)
						found = base_recipe(value)
						return found unless found.nil?
					end
				end
			elsif data.is_a?(Array)
				data.each do |item|
					found = base_recipe(item)
					return found unless found.nil?
				end
			end
			nil
		end

end

app/helpers/recipes_helper.rb
module RecipesHelper
		#sets what the recipe will display with whole numbers or fractions
		def display_time(time)
			if time % 1 != 0
				whole_number = time.to_i
				fraction = (time % 1).to_r.rationalize(0.01)

				display_time = "#{whole_number} #{fraction}"
			else
				whole_number = time.to_i
				display_time = "#{whole_number}"
			end
		end


		def total_time_display(ptime, ptd, ctime, ctd, rtime, rtd)
			if ptd == "hr"
				ptime = ptime.to_f * 60
			end
			if ctd == "hr"
				ctime = ctime.to_f * 60
			end
			if rtd == "hr"
				rtime = rtime.to_f * 60
			end
			total_time = ptime.to_f + ctime.to_f + rtime.to_f

			if total_time > 60
				hours = (total_time / 60).to_i
				minutes = (total_time % 60).to_i
				if hours > 1
					total_time_descriptor = "#{hours} hrs #{minutes} min"
				else
					total_time_descriptor = "#{hours} hr #{minutes} min"
				end
			else
				total_time_description = "#{total_time.to_i} min"
			end
		end

end

app/views/recipes/_discover_carousel.html.slim
#discover-carousel.carousel.slide data-bs-ride="carousel"
	.carousel-inner
		- @carousel.each_with_index do |recipe, i|
			-if i == 1
				=link_to recipe_path(recipe), class: "carousel-item carousel-card active"
					- if recipe.header.attached?
						= image_tag(recipe.header)
					- else
						= image_tag("empty-plate.jpg")
					.carousel-title-background.pt-4.ps-5.pe-5
						.carousel-title
							= "#{recipe.name}"
			-else
				=link_to recipe_path(recipe), class: "carousel-item carousel-card"
					- if recipe.header.attached?
						= image_tag(recipe.header)
					- else
						= image_tag("empty-plate.jpg")
					.carousel-title-background.pt-4.ps-5.pe-5
						.carousel-title
							= "#{recipe.name}"

		button.carousel-control-prev type="button" data-bs-target="#discover-carousel" data-bs-slide="prev"
			span.carousel-control-prev-icon aria-hidden="true"
			span.visually-hidden Previous

		button.carousel-control-next type="button" data-bs-target="#discover-carousel" data-bs-slide="next"
			span.carousel-control-next-icon aria-hidden="true"
			span.visually-hidden Next

app/views/recipes/_discover_search_form.slim
= search_form_for @q do |f|
	.row.mb-2
		.input-group
		  = f.search_field :name_or_description_or_ingredients_ingredient_or_tags_name_cont, placeholder: "Search for a recipe!", class: "discover-search form-control"

app/views/recipes/_form.html.slim
.container
	= form_with model: @recipe, id: "recipe-form" do |f|
		.row.mb-3
			.field.w-100
				#form-recipe-name
					=f.label :name
				=f.text_field :name, class: "form-control"

			.field
				#form-recipe-description
					=f.label :description
				=f.text_area :description, class: "form-control"

			/ .field
			/ 	#recipe-image-upload
			/ 		=f.label "Upload a picture"
			/ 	=f.file_field :pictures, multiple: true

			.field
				#recipe-image-upload
					=f.label "Upload a Picture"
				=f.file_field :header

			.field
				#form-recipe-prep-time.input-group
					=f.label :prep_time
				.row
					.col
						=f.number_field :prep_time, step: 0.25, class: "form-control"
					.col-3
						=f.select :prep_time_descriptor, ["min", "hr"], {},  class: "form-select"

			.field
				#form-recipe-prep-time
					=f.label :cook_time
				.row
					.col
						=f.number_field :cook_time, step: 0.25, class: "form-control"
					.col-3
						=f.select :cook_time_descriptor, ["min", "hr"], {},  class: "form-select"


			.field
				#form-recipe-prep-time
					=f.label :rest_time
				.row
					.col
						=f.number_field :rest_time, step: 0.25, class: "form-control"
					.col-3
						=f.select :rest_time_descriptor, ["min", "hr"], {},  class: "form-select"


			.field
				#form-recipe-prep-time
					=f.label :calories
				=f.text_field :calories, class: "form-control"

		#recipe_ingredients.mb-4
			fieldset
				legend Ingredients
				#sort-ingredients
					= f.fields_for :ingredients, @recipe.ingredients.order(:order_number) do |ingredient|
						= render "ingredient_fields", f: ingredient
					div
						= link_to_add_association "Add Ingredient", f, :ingredients, class: "btn btn-outline-primary no-sort links", id: "#add-ingredients-button"

		#recipe_instructions.mb-4
			fieldset
				legend Instructions

				#sort-instructions
					= f.fields_for :instructions, @recipe.instructions.order(:step_number) do |instruction|
						= render "instruction_fields", f: instruction
					div
						= link_to_add_association "Add Step", f, :instructions, class: "btn btn-outline-primary no-sort links", id: "#add-instructions-button"

		#recipe-tags
			fieldset
				legend Tags

			.field
				=f.select :tag_ids, Tag.all.map { |t| [t.name, t.id] }, {include_blank: false}, {:multiple => true, class: 'tag-multiple form-control'}

		#original-recipe-photos.mb-5
			fieldset
				legend Original Recipe Photos

			.field
				=f.file_field :original_recipe_photos, multiple: true

		.actions.mar-top-15
			= f.submit class: "btn btn-outline-success", id: "recipe-submit"

app/views/recipes/_ingredient_fields.slim
.nested-fields.ingredients-sortable
	= f.hidden_field :_destroy
	= f.hidden_field :order_number, class: "position"
	.row
		.col.input-group
			.btn.btn-outline-secondary.grip
				i class="bi bi-grip-horizontal"
			= f.text_field :ingredient, placeholder: "Ingredient", class: "form-control"
			= link_to_remove_association "", f, class: "remove_fields btn btn-outline-secondary bi bi-x-circle"

app/views/recipes/_new_recipe_card.html.slim
= link_to recipe, class: "col-lg-3 no-decoration mb-3"
	.recipe-box-wrapper
		.recipe-card-picture
			- if recipe.header.attached?
				= image_tag(recipe.header)
			- else
				= image_tag("empty-plate.jpg")
		.recipe-card-words.pt-1.pe-1
			.recipe-name
				= "#{recipe.name}"

			.recipe-creator
				= "By "

				b.span.recipe-creator-name
					= "#{recipe.user.username}"

			.recipe-description
				= "#{recipe.description}"

app/views/recipes/_recipe_card.html.slim
= link_to recipe, class: "col-lg-4 no-decoration mb-3"
	.recipe-box-container
		.recipe-card-picture
			- if recipe.header.attached?
				= image_tag(recipe.header)
			- else
				= image_tag("empty-plate.jpg")
		.recipe-card-words.p-2
			.recipe-name
				= "#{recipe.name}"

			.recipe-creator
				= "By "

				b.span.recipe-creator-name
					= "#{recipe.user.username}"

			.recipe-description
				= "#{recipe.description}"

app/views/recipes/_search_form.slim
= search_form_for @q, class: "row row-cols-lg-auto g-3 align-items-center" do |f|
	.row.mb-2
		.input-group
			= f.search_field :name_or_description_or_tags_name_cont, placeholder: "Search for a recipe!", class: "form-control"
			/ = f.search_field :name_or_description_or_ingredients_name_or_tags_name_cont, placeholder: "Search for a recipe!", class: "form-control"
			= f.submit class: "btn btn-outline-secondary"

app/views/recipes/discover.html.slim
.container.mt-5
	.row
		.col-sm-1

		.col-lg-10
			.row.wrapper
				.col-lg-6
					.content-header
						h1 Happea Cook
				.col-lg-6
					.content-link
						= render 'discover_search_form'
			.row
				=render "discover_carousel"


			.row.mt-4
				.wrapper
					.content-header
						= "Categories"
					.content-link
						=link_to "See All >", tags_path

			.row.mt-1
				.col-lg-6
					.row
						.col-sm-3.mb-2
							=link_to tag_recipes_path(@breakfast), class: "no-decoration"
								.category-card
									.category-icon
										=image_tag("categoryIcons/breakfast.png")
									.category-content
										= "Breakfast"

						.col-sm-3.mb-2
							=link_to tag_recipes_path(@dinner), class: "no-decoration"
								.category-card
									.category-icon
										=image_tag("categoryIcons/dinner.png")
									.category-content
										= "Dinner"

						.col-sm-3.mb-2
							=link_to tag_recipes_path(@sides), class: "no-decoration"
								.category-card
									.category-icon
										=image_tag("categoryIcons/side-dishes.png")
									.category-content
										= "Side Dishes"

						.col-sm-3.mb-2
							=link_to tag_recipes_path(@snacks), class: "no-decoration"
								.category-card
									.category-icon
										=image_tag("categoryIcons/snacks.png")
									.category-content
										= "Snacks"


				.col-lg-6
					.row
						.col-sm-3.mb-2
							=link_to tag_recipes_path(@bread), class: "no-decoration"
								.category-card
									.category-icon
										=image_tag("categoryIcons/bread.png")
									.category-content
										= "Bread"

						.col-sm-3.mb-2
							=link_to tag_recipes_path(@dessert), class: "no-decoration"
								.category-card
									.category-icon
										=image_tag("categoryIcons/dessert.png")
									.category-content
										= "Dessert"

						.col-sm-3.mb-2
							=link_to tag_recipes_path(@drinks), class: "no-decoration"
								.category-card
									.category-icon
										=image_tag("categoryIcons/drinks.png")
									.category-content
										= "Drinks"

						.col-sm-3.mb-2
							=link_to tag_recipes_path(@christmas), class: "no-decoration"
								.category-card
									.category-icon
										=image_tag("categoryIcons/christmas.png")
									.category-content
										= "Christmas"

			.row.mt-5.wrapper
				.col-lg-6
					.content-header
						= "Discover Recipes"
				.col-lg-6




			.row.mt-3
				- @recipes.each do |recipe|
					= render 'new_recipe_card', recipe: recipe


				= paginate @recipes, theme: 'bootstrap-5'

		.col-sm-1

app/views/recipes/edit.html.slim
.container
	.row
		.col-sm-2
		.col-lg-8
			h1
				= "Editing Recipe"

			= render 'form', recipe: @recipe

			= link_to 'Show | ', @recipe
			= link_to 'Back', recipes_path

		.col-sm-2

app/views/recipes/import.html.slim
.container
	.row
		.col-sm-2
		.col-lg-8
			h1
				= "Import Recipe"

			= render 'form', recipe: @recipe

			= link_to 'Back', recipes_path
		.col-sm-2

app/views/recipes/import_recipe.html.slim
.import-recipe-form
  .row 
    .col-sm-2
    .col 
      h1 Import Recipe From URL
      
    .col-sm-2
    / = form_with model: @user, url: manage_user_path do |form|
  = form_with model: @recipe, url: import_recipes_path do |form|
    .row
      .col-sm-2
      .col.input-group
        = form.url_field :name, placeholder: "Recipe URL", class: "form-control"
        = form.submit "Import Recipe", class: "btn btn-outline-success"
      .col-sm-2

app/views/recipes/index.html.slim
.container
	.row
		h1 Recipes

	.row
		.col-lg-6
			= render 'discover_search_form'

	.row
		- @recipes.each do |recipe|
			= render 'new_recipe_card', recipe: recipe


		= paginate @recipes, theme: 'bootstrap-5'

app/views/recipes/my_recipes.html.slim
.container
	.row
		h1 Recipes

	.row
		= render 'search_form'

	.row
		- @recipes.each do |recipe|
			= render 'recipe_card', recipe: recipe

		= paginate @recipes, theme: 'bootstrap-5'

app/views/recipes/new.html.slim
.container
	.row
		.col-sm-2
		.col-lg-8
			h1
				= "New Recipe"

			= render 'form', recipe: @recipe

			= link_to 'Back', recipes_path
		.col-sm-2