config/routes.rb
Rails.application.routes.draw do
	get 'users/index'
	resources :tags do
			get '/recipes', to: 'tags#tag_recipes'
			collection do
				get :list
			end
	end

	resources :manage_users
	resources :manage_recipes

	resources :instructions
	resources :ingredients
	resources :recipes do
		collection do
			get :my_recipes
				get :discover
				get :import_recipe
				post :import
		end
	end
	devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

	root 'recipes#discover'
end

app/controllers/manage_recipes_controller.rb
class ManageRecipesController < ApplicationController
    before_action :set_recipe, only: %i[ show edit update destroy ]
    before_action :authenticate_user!, only: %i[ new edit create udpate destroy ]
  
    # GET /recipes or /recipes.json
    def index
        @recipes = Recipe.all
    end
  
    # DELETE /recipes/1 or /recipes/1.json
    def destroy
        if @recipe.user_id == current_user.id
            @recipe.destroy

            respond_to do |format|
            format.html { redirect_to manage_recipes_url, notice: "Recipe was successfully destroyed." }
            format.json { head :no_content }
            end
        else
            redirect_to @recipe, notice: "You do not have permission to delete this recipe"
        end
    end
  
    private
        # Use callbacks to share common setup or constraints between actions.
        def set_recipe
            @recipe = Recipe.find(params[:id])
        end
    
        # Only allow a list of trusted parameters through.
        def recipe_params
            params.require(:recipe).permit(:name, :user_id, :description, :servings, :prep_time, :prep_time_descriptor, :cook_time, :cook_time_descriptor, :rest_time, :rest_time_descriptor, :total_time, :total_time_descriptor, :calories, :page, :header, :tag_list, :tag, {tag_ids: []}, :tag_ids, :ingredient_id, ingredients_attributes: [:_destroy, :id, :ingredient, :order_number], instructions_attributes: [:_destroy, :id, :step_number, :step], pictures: [], original_recipe_photos: [])
        end

  end
  

app/views/manage_recipes/_form.html.slim
= form_with model: @user, url: manage_user_path do |form|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - user.errors.each do |error|
          li = error.full_message


  .field
		.form-label
    	= form.label :username
		= form.text_field :username, class: "form-control"

  .field
		.form-label
    	= form.label :email
		= form.text_field :email, class: "form-control"

  .field
		.form-label
    	= form.label :super_user
		.form-check.form-switch
			= form.check_box :super_user, class: "form-check-input", type: "checkbox"
			/
			/ - if current_user.id == @user.id
			/ 	= form.check_box :super_user, class: "form-check-input", type: "checkbox",  disabled: true
			/ - else
			/ 	= form.check_box :super_user, class: "form-check-input", type: "checkbox"

  .actions
    = form.submit class: "btn btn-primary"

app/views/manage_recipes/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', manage_user_path(@user) %> |
<%= link_to 'Back', tags_path %>

app/views/manage_recipes/index.html.slim
p#notice
	= notice

h1 Recipes

table.table.table-hover
  thead
		tr
			th Name
			th User
			th 
			th
			th
			th


  tbody
     - @recipes.each do |recipe|
      tr
				td = recipe.name
				td = recipe.user.username
				td 
				td = link_to 'Show', recipe_path(recipe)
				td = link_to 'Edit', edit_recipe_path(recipe)
				td = link_to 'Destroy', manage_recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' }

app/views/manage_recipes/list.html.slim
p#notice
	= notice

h1 Tags

table.table
  thead
    tr
      th Name
      th colspan="4"

  tbody
     - @tags.each do |tag|
      tr
				td = tag.name
				td = link_to 'Show Recipes', tag_recipes_path(tag)
				td = link_to 'Show', tag
				td = link_to 'Edit', edit_tag_path(tag)
				td = link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }
<br>

= link_to 'New Tag', new_tag_path

app/views/manage_recipes/new.html.erb
<h1>New Tag</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', tags_path %>

app/views/manage_recipes/show.html.slim
p#notice
	= notice


table.table.table-hover
  thead
		tr
			th Username
			th Email
			th Super User
			th
			th


  tbody
    tr
			td = @user.username
			td = @user.email
			td = @user.super_user
			td = link_to 'Edit', edit_manage_user_path(@user)
			td = link_to 'Destroy', manage_user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }

app/views/manage_recipes/tag_recipes.html.slim
.container
	.row
		h1
			= "#{@tag.name}"

	.row
		- @tag_recipes.each do |recipe|
			= link_to recipe, class: "col-lg-4 no-decoration"
				.recipe-box-container
					.recipe-name
						= "#{recipe.name}"

					.recipe-creator
						= "By "

						b.span.recipe-creator-name
							= "#{recipe.user.username}"

					.recipe-description
						= "#{recipe.description.truncate(120, separator: ' ')}"

		= paginate @tag_recipes, theme: 'bootstrap-5'