config/routes.rb
Rails.application.routes.draw do
	get 'users/index'
	resources :tags do
			get '/recipes', to: 'tags#tag_recipes'
			collection do
				get :list
			end
	end

	resources :manage_users
	resources :manage_recipes

	resources :instructions
	resources :ingredients
	resources :recipes do
		collection do
			get :my_recipes
				get :discover
				get :import_recipe
				post :import
		end
	end
	devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

	root 'recipes#discover'
end

app/views/layouts/_nav.slim
nav.navbar.navbar-expand-lg.happeacook-nav
  .container-fluid
		.navbar-brand
			= link_to "Happea Cook", discover_recipes_path

		.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
			span.navbar-toggler-icon


		#navbarSupportedContent.collapse.navbar-collapse.justify-content-center
			ul.navbar-nav.me-auto.mb-2.mb-lg-0
				li.nav-item
					.nav-link
						=link_to "Recipes", recipes_path
				-if user_signed_in?
					li.nav-item.dropdown
						a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" New Recipe
						ul.dropdown-menu
							li.dropdown-item
								= link_to 'Create Your Own', new_recipe_path
							li.dropdown-item
								= link_to 'Import', import_recipe_recipes_path
				li.nav-item
					.nav-link
						=link_to "Categories", tags_path

				-if user_signed_in?
					-if current_user.super_user?
						li.nav-item.dropdown
							a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" Admin
							ul.dropdown-menu
								li.dropdown-item
									= link_to 'Manage Tags', list_tags_path
								li.dropdown-item
									= link_to 'Manage Users', manage_users_path
								li.dropdown-item
									= link_to 'Manage Recipes', manage_recipes_path


				li.nav-item.dropdown
					a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" Account
					ul.dropdown-menu
						-if user_signed_in?
							li.dropdown-item
								= link_to 'My Recipes', my_recipes_recipes_path
							li.dropdown-item
								= link_to 'Edit profile', edit_user_registration_path
							li.dropdown-item
								= link_to "Logout", destroy_user_session_path, method: :delete

						-else
							li.dropdown-item
								= link_to "Login", new_user_session_path

app/views/layouts/_test_nav.html.slim
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title Happea Cook
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

	= favicon_link_tag 'favicon.png'
	= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
	= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
	= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

	


  body
		= render "layouts/nav"

		- if notice
		  p.alert.alert-success
				= notice
		- if alert
		  p.alert.alert-danger
				= alert

		.container.content.mb-5
			= yield

		footer.footer.mt-auto.py-3